openapi: 3.1.0
info:
  version: 1.0.0
  title: Plantlog
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 
    This is a documentation of Plantlog app
tags:
  - name: Plants
    description: Operations about plants.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
paths:
  /plants:
    get: 
      $ref: ../swagger/paths/plants/getAll.yaml
    post:
      $ref: ../swagger/paths/plants/postPlant.yaml
  /plants/own:
    get: 
      $ref: ../swagger/paths/plants/getOwn.yaml
  /plants/favorites:
    get: 
      $ref: ../swagger/paths/plants/getUserFav.yaml
    post:
      $ref: ../swagger/paths/plants/{id}/toggleFavPlant.yaml
  /plants/{id}:
    get: 
      $ref: ../swagger/paths/plants/{id}/getPlantById.yaml
    patch: 
      $ref: ../swagger/paths/plants/{id}/patchPlant.yaml
    delete: 
      $ref: ../swagger/paths/plants/{id}/deletePlant.yaml
  /auth/signup:
    post:
      $ref: ../swagger/paths/auth/signUp/post.yaml
  /auth/signin:
    post:
      $ref: ../swagger/paths/auth/signIn/post.yaml
  /auth/verify:
    get:
      $ref: ../swagger/paths/auth/verify/get.yaml
  /auth/signout:
    post:
      $ref: ../swagger/paths/auth/signout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/resetPasswordEmail:
    post:
      $ref: ../swagger/paths/auth/resetPasswordEmail/post.yaml
  /auth/resetPsw:
    post:
      $ref: ../swagger/paths/auth/resetPsw/post.yaml
  /auth/getOAuthURL:
    get:
      $ref: ../swagger/paths/auth/getOAuthURL/get.yaml
  /auth/confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/confirm-oauth/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer